apiVersion: v1
kind: Namespace
metadata:
  name: psicorose
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: psicorose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: placeholder/psicorose-backend:latest # GitHub Actions will update this
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: psicorose-secrets
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: psicorose-secrets
              key: jwt-secret
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: psicorose-secrets
              key: email-user
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: psicorose-secrets
              key: email-pass
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: psicorose-secrets
              key: gemini-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: psicorose
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
